RED_COLOR = "indianred"
DARK_CREAM_COLOR = "#FAF0E6"
LIGHT_CREAM_COLOR = "#FFFAF0"
POLICE = "Garamond"
BTN_SIZE_X = 20
BTN_SIZE_Y = 10
EMPTY_TABLE = "Pas de table disponible."
EMPTY_RESERVATION = "Pas de réservations"
EMPTY_NOTIFICATION = "Pas de notifications"
selected_tables = []  # Liste pour stocker les tables sélectionnées
HOUR_TO_MINUTE = 60
LATE_RESERVATION = 15
OCCUPE = "X"
DISPONIBLE = "V"
IN_PROGRESS = "P"
WAITING = "W"
